targets:
  $default:
    builders:
      api_generator:
        enabled: true

builders:
  http_api:
    import: "package:json_parse_test/builder.dart"
    builder_factories: ["httpDataBuilder"]
    build_extensions: {".dart": [".http_api.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

#builders:
#  httpDataBuilder:
#    import: "package:json_parse_test/builder.dart"
#    builder_factories: ["httpDataBuilder"]
#    build_extensions: {".dart": [".h.part"]}
#    auto_apply: root_package
#    build_to: source

