name: json_parse_test
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  analyzer: '>=0.39.0 <0.42.0'
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'

  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  # For v3 only – allow a wide range since the only change was to REMOVE things
  # from json_annotation
  json_parse_annotion:
    path: ../json_parse_annotion/
  meta: ^1.1.0
  path: ^1.3.2
  source_gen: ^0.9.6

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  collection: ^1.14.0
  dart_style: ^1.2.0
  logging: ^0.11.3+1
  pub_semver: ^1.4.0
  source_gen_test: ^0.1.0
  test: ^1.6.0
  yaml: ^2.1.13
